openvinotoolkit/telemetry

- README.md
- src/backend/backend.py
- src/backend/backend_ga.py
- src/main.py
- src/utils/isip.py
- src/utils/sender.py
- src/utils/sender_test.py
Fixed problems from bandit, corrected readme.
> Fixed problems from bandit, corrected readme.

- setup.py
Description:
Corrected version, corrected license format.
Ticket: 68494
> Corrections of setup.py

- src/backend/backend_ga.py
- src/main.py
Removed TID from library.
Ticket: 68693
> Removed TID from library.

- README.md
Changed package name.
Intel® Distribution of OpenVINO™ Toolkit Telemetry -> OpenVINO™ telemetry
> Changed package name.

- src/utils/guid.py
- src/utils/opt_in_checker.py
- src/utils/opt_in_checker_test.py
Description:
Refactored create_or_check_isip_dir() as was asked in https://github.com/openvinotoolkit/telemetry/pull/20.
Added try..except blocks for os.remove() and os.mkdir().
Corrected warning message during generation of guid file.
Ticket: 76655
> Corrections of create_or_check_isip_dir() method.

- src/main.py
Description:
Updated package version to 2022.1.1
> Updated package version to 2022.1.1

- src/backend/backend_ga.py
- src/main.py
- src/utils/guid.py
- src/utils/opt_in_checker.py
- src/utils/sender.py
Logger library was used to print warnings.
Ticket: 81482
> Logger was used to print warnings.

- src/utils/opt_in_checker.py
Updated dialog message.
Ticket 78624
> Updated dialog message.

- src/utils/opt_in_checker.py
- src/utils/opt_in_checker_test.py
Changed isip file name. 
Ticket: 93843
> Change isip file format

- src/main.py
Added explicit check that Telemetry is run by Openvino tool. 
Allowed cmd tools: MO, POT, AC, MD.
> Added check if script is openvino tool.

- src/utils/sender.py
- src/utils/sender_test.py
Fixed sender to not break if event is sent after shutdown.
> Fixed sender to not break if event is sent after shutdown.

- src/backend/backend_ga_test.py
- src/main.py
- src/utils/guid.py
- src/utils/opt_in_checker.py
- src/utils/opt_in_checker_test.py
Renamed isip file to openvino_telemetry.
> Renamed isip file to openvino_telemetry.

- setup.py
- src/__init__.py
- src/backend/__init__.py
- src/backend/backend.py
- src/backend/backend_ga.py
- src/backend/backend_ga_test.py
- src/main.py
- src/opt_in_out.py
- src/utils/__init__.py
- src/utils/colored_print.py
- src/utils/guid.py
- src/utils/input_with_timeout.py
- src/utils/input_with_timeout_test.py
- src/utils/message.py
- src/utils/opt_in_checker.py
- src/utils/opt_in_checker_test.py
- src/utils/sender.py
- src/utils/sender_test.py
> Updated copyright headers.

- src/main.py
Updated telemetry version to 2023.1.0
> Updated telemetry version to 2023.1.0

- src/main.py
- src/main_test.py
- Fix of logic of disabling opt-in dialog in demo applications.
- Ticket: CVS-114975
> Fix of logic of disabling opt-in dialog in demo applications.

- src/main.py
> Version update.

- src/main.py
- src/main_test.py
- src/utils/opt_in_checker.py
- src/utils/opt_in_checker_test.py
Added opt-out approach to Telemetry.
Ticket: 110429
> Added opt-out approach to Telemetry.

- .github/workflows/bandit.yml
- src/backend/backend_ga.py
- src/backend/backend_ga4.py
- src/main_test.py
- src/utils/opt_in_checker_test.py
- src/utils/params.py
Fixed bandit issues.
Added bandit workflow.
Tickets: 114074, 117422, 121511
> Fixed bandit issues.

- src/main.py
> Updated version to 2023.2.0.

- src/main.py
> Update version to 2023.2.1.

- src/backend/backend_ga.py
- src/backend/backend_ga4.py
- src/utils/cid.py
- src/utils/sender.py
Remove not needed messages from log, as they are confusing for user.
> Remove not needed messages from log.

- src/backend/backend_ga.py
- src/backend/backend_ga4.py
- src/main.py
- src/utils/opt_in_checker.py
Silence errors to not interrupt the outer pipeline
Ticket: CVS-154805
> Silence errors to not interrupt the outer pipeline

- src/main.py
> Updated version to 2024.5.

- src/main.py
> Updated version to 2025.0

- src/main.py
Fixed logic for read-only intel dir.
> Fixed logic for read-only intel dir.

- .github/workflows/precommit.yml
- Dockerfile
- src/backend/backend_ga4.py
- src/backend/backend_ga4_test.py
- src/main_test.py
Docker check.
Ticket: CVS-158404
> Docker check.

- src/main.py
> Updated version.
